{{- $es := .Values.externalSecret | default dict -}}
{{- if and .Values.config.apiKey (not .Values.config.existingSecret) (not $es.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyperping-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperping-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.config.apiKey | b64enc | quote }}
{{- end }}
